### ISSUE TITLE
Start Page Error

### ISSUE THREAD

**Issue by espresso0000** [SuperPWA/Super-Progressive-Web-Apps#29] opened 2018-04-28 05:07 UTC
After latest update, my start page isn't opening correct page, opens a random image gallery.  I've tryed deleting pwa and reinstalling.  Cleared all caches, change start page setting, nothing changes it.  Also don't see startpage change in manifest no matter what is selected.  Suggestions?
https://caves.org/survey/ics/

**Comment by espresso0000** [comment] 2018-04-28 08:38
Had to manually change the manifest to "start_url":"./"  per your fantastic email support.  Posting in case anyone else has similar problem.

**Comment by josevarghese** [comment] 2018-04-28 09:04
Glad to know that the issue is resolved via email @espresso0000. This is a case when the WordPress is installed within a folder of the website, we will resolve this issue on our coming update.

Thanks a lot to hear that you liked our support too.

**Closed** 2018-05-03 05:53 UTC
Labels: bug

**Comment by arunbasillal** [comment] 2018-05-03 05:59
Hello @espresso0000 Please test this out and confirm. Thanks.
