### ISSUE TITLE
PHP Notice: Array to string conversion

### ISSUE THREAD

**Issue by Daniel-Richard** [SuperPWA/Super-Progressive-Web-Apps#104] opened 2019-04-27 18:03 UTC
PHP error notice found on WooCommerce > Orders

WooCommerce 3.6.2
WordPress 5.1.1
SuperPWA 2.0.2

Hope this helps!

```
WP_Posts_List_Table->prepare_items()
wp-admin/edit.php:198
wp_edit_posts_query()
wp-admin/includes/class-wp-posts-list-table.php:146
wp()
wp-admin/includes/post.php:1174
WP->main()
wp-includes/functions.php:1105
WP->parse_request()
wp-includes/class-wp.php:737
do_action_ref_array('parse_request')
wp-includes/class-wp.php:387
superpwa_generate_sw_and_manifest_on_fly()
wp-includes/class-wp-hook.php:286
implode()
wp-content/plugins/super-progressive-web-apps/admin/basic-setup.php:415
wp-content/plugins/super-progressive-web-apps/admin/basic-setup.php:415
```

![2019-04-28_015144](https://user-images.githubusercontent.com/14333530/56853341-d13d3a00-6958-11e9-9943-f9c9508363e8.png)

**Comment by arunbasillal** [comment] 2019-07-08 17:36
Duplicate of #92

**Closed by arunbasillal** 2019-07-08 17:36 UTC
