### ISSUE TITLE
Fix Apple splash screen (white screen) issue

### ISSUE THREAD

**Issue by tamerxkilinc** [SuperPWA/Super-Progressive-Web-Apps#57] opened 2018-09-23 20:06 UTC
Hello everybody,

I noticed that there is a feature which Apple provides but this plugin does not use.
As mentioned in the [apple developers docs](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html), we are able to add a splash screen to our PWAs on iOS devices. When no specific splash screen is provided, apple inserts a complete white screen which doesn't look good and shows a huge difference between a native app and a PWA. 

With this line of code we can provide a custom splash screen:
`<link rel="apple-touch-startup-image" href="/launch.png">`
Of course we have to provide different images for different screen sizes which are listed [here](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/).

With this feature we would get one step closer to native app experience on iOS.

**Comment by josevarghese** [comment] 2018-09-23 20:18
A solution for splash screen is already within our beta (also can be noticed at our [website](https://superpwa.com) ) and most probably you can expect the same on the coming versions of SuperPWA WordPress plugin.

**Comment by kashann** [comment] 2019-09-29 23:51
Hello! Is it fixed? I don't seem to get it working.

**Comment by mzrLab** [comment] 2020-06-13 19:36
hey there 
I had this problem and I was stuck for 4 hours searching about "PWA ios splash screen not working"
and I found this medium article which was really helpful [](https://medium.com/appscope/adding-custom-ios-splash-screens-to-your-progressive-web-app-41a9b18bdca3)

Apple does not yet support the web manifest specification and instead leans on its classic touch-icon mechanism. This works, you just need to be aware you still need to include the META tags to drive that experience.

**Comment by akshaywali** [comment] 2022-12-06 07:14
This issue is duplicate of ticket https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/343 IOS splashcreen Icon not working

**Closed by akshaywali** 2022-12-06 07:14 UTC
Labels: bug
