### ISSUE TITLE
Session got logout when user go out of PWA

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#528] opened 2024-05-17 10:49 UTC
When we logged in PWA and then after going out from it and after clearing cache, when again go through PWA then it automatically got logout.

Reference user -:https://magazine3.in/conversation/274975?folder_id=23

**Comment by Sanjeevsetu** [comment] 2024-05-30 05:28
This issue seems invalid. It works perfectly and user is using SuperPwa so I am closing it

**Comment by Sanjeevsetu** [comment] 2024-05-31 11:28
The issue is not valid. There was some setup issue at user end and now it works fine.

**Closed by Sanjeevsetu** 2024-05-31 11:28 UTC
Labels: bug, high
